[managers]
docker-swarm-01 ansible_host=10.0.39.100
docker-swarm-02 ansible_host=10.0.39.101
docker-swarm-03 ansible_host=10.0.39.102

[workers]
docker-worker-01 ansible_host=10.0.39.120
docker-worker-02 ansible_host=10.0.39.121
docker-worker-03 ansible_host=10.0.39.122

[swarm:children]
managers
workers

[swarm:vars]
ansible_user=connect
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
