apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-nfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: test-nfs-pod
spec:
  containers:
    - name: app
      image: busybox
      command:
        - sh
        - -c
        - "echo 'Teste de escrita no NFS em $(date)' > /mnt/nfs/teste.txt && sleep 3600"
      volumeMounts:
        - mountPath: "/mnt/nfs"
          name: nfs-volume
  volumes:
    - name: nfs-volume
      persistentVolumeClaim:
        claimName: test-nfs-pvc
